version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Pacific/Auckland
    target-branch: master
    groups:
      patch-updates:
        update-types:
          - patch
